### ISSUE TITLE
Site HTML and CSS needs to be rewritten in Bootstrap.

### ISSUE THREAD

**Issue by DrewWarrenTIY** [fee-slc-2016/tiy-slc-fee-2016#2]
Since we want to eventually have a carousel and some other javascript elements that are conveniently and easily utilized via Bootstrap, we might as well mock up the wire frame in Bootstrap so it is ready for the features when we want to implement them.

**Comment by JoniWeiss** [comment]
Resolved with 6782279 merge request.
