### ISSUE TITLE
About button needs basic information

### ISSUE THREAD

**Issue by matsad3547** [fee-slc-2016/tiy-slc-fee-2016#32]
Here's my suggestion: 

"We are a diverse group of women and men studying together with the aim of entering the professional world of web development.  We are studying under the tutelage of Sean Duncan, Javascript craftsman extraordinaire and professional educator.  We think the work showcased here speaks for itself."

Please comment with suggestions!

**Comment by SurlyMae** [comment]
Needs a period after itself :) 
Sounds fine to me!

**Comment by matsad3547** [comment]
@SurlyMae fixed!

**Comment by metasean** [comment]
A couple of suggestions:
1. Maybe instead of "We are a diverse group of women and men..." do "We are a diverse group of people..."   (the explicit women and men seems odd to me)
2. This page is about you and your projects, so feel free to remove the second sentence ;-)

**Comment by SurlyMae** [comment]
We spent twelve weeks at The Iron Yard studying the ins and outs of front-end development, and are ready to conquer the tech world!\* 
*Ready for our first junior dev positions.

**Comment by matsad3547** [comment]
Further design rendered about section redundant
