### ISSUE TITLE
Create a social media/photos area to include photos of us being amazing

### ISSUE THREAD

**Issue by kfurness** [fee-slc-2016/tiy-slc-fee-2016#40]

**Comment by SurlyMae** [comment]
![img_6444](https://cloud.githubusercontent.com/assets/17370135/20362129/a1bf066c-abf7-11e6-9a41-5709c219e265.JPG)
![img_6452](https://cloud.githubusercontent.com/assets/17370135/20362131/a4b52964-abf7-11e6-9788-c143bd4d1dce.JPG)
![img_6454](https://cloud.githubusercontent.com/assets/17370135/20362595/6930f4de-abf9-11e6-98a3-2c92b2de5c7b.JPG)
