### ISSUE TITLE
Fix the page title & header group title

### ISSUE THREAD

**Issue by metasean** [fee-slc-2016/tiy-slc-fee-2016#45]
Change the page's title to something relevant instead of "Bootstrap Example".

**Comment by DrewWarrenTIY** [comment]
Head Title:
"TIY-FEE-2016 Group Portfolio"

Jumbotron Header:
"Duncan's Octo-Monsters"

**Comment by SurlyMae** [comment]
Head Title:
WebDev Group Portfolio

Jumbotron header: 
Front-End Engineering Grads, 2016

-We will point out in the about us that we attended The Iron Yard. 
-No one is going to know who 'Duncan' is, and as an adult I feel a bit ridic being referred to as a wizard, octopus, duckling, etc :)

**Comment by JoniWeiss** [comment]
"I came for the pizza. I stayed for the coding."

**Comment by trrapp12** [comment]
Name suggestions:

Silicon Students
Silicon Soldiers
Codeskill
Code Engineering Optimists (CEO)
Reuser Personas 
Techlarations (play on Declarations)
SDK (figure an acronymn with students, students doing kode)
SKK students killing kode
Call to Action
Growth Hackers
.REV(O){LUTION}
