### ISSUE TITLE
Create a one liner describing yourself

### ISSUE THREAD

**Issue by kfurness** [fee-slc-2016/tiy-slc-fee-2016#55]
Do not go above 140 characters!

**Comment by trrapp12** [comment]
(function trevorRapp ( ) { while (awake) { return code( ) })( );

**Comment by DrewWarrenTIY** [comment]
I'm here to chew bubble gum and write code that impacts and improves the world... and I'm all out of bubble gum.

**Comment by SurlyMae** [comment]
I'm coming to development from an accounting and management background, and having a blast making the switch. I love Mondays!

**Comment by matsad3547** [comment]
I'm excited to join the wild world of web development.

**Comment by kfurness** [comment]
Crazy about flexibility and Flexbox! When I'm not coding, I'm running away with the circus.

**Comment by KevinUtah** [comment]
Recovering Secondary Mathematics Teacher, Educational Administrator, and Educational Consultant. I enjoy hiking and snowshoeing with my wife.

**Comment by JoniWeiss** [comment]
"I came for the pizza. I stayed for the coding."

**Comment by Svartingknas** [comment]
talk is cheap, show me the code.
if (!=tired()) { keepCoding();} else { drinkCoffee();}
Ready to contribute to the world of developing.
