### ISSUE TITLE
Cross-browser compatibility

### ISSUE THREAD

**Issue by trrapp12** [fee-slc-2016/tiy-slc-fee-2016#8]
User should be able to have a similar experience across Chrome, FireFox, IE10, Opera, and Safari.

**Comment by DrewWarrenTIY** [comment]
Chrome, Firefox and Safari have been tested as of 10/27 and all look the same. Thumbs Up!

**Comment by JoniWeiss** [comment]
Tested in IE10, MS Edge, and Opera. All tests pass! 
Closing this issue as testing has completed successfully.
